services:
  postgres:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  django:
    container_name: django
    build: ./django
    volumes:
      - ./django:/usr/src/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
    command: |
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python -m daphne -b 0.0.0.0 --port 8000 config.asgi:application"
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  postgres-data:
