services:
  postgres:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgresdjangoecs
  django:
    container_name: django
    build: ./django
    volumes:
      - ./django:/usr/src/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgresdjangoecs
      - POSTGRES_PORT=5432
    # command: |
    #   bash -c "python manage.py makemigrations &&
    #   python manage.py migrate &&
    #   python manage.py runserver 0.0.0.0:8000"
    tty: true
    ports:
      - 8000:8000
    # command: |
    #   bash -c "python manage.py collectstatic --noinput &&
    #   python manage.py makemigrations &&
    #   python manage.py migrate &&
    #   gunicorn myapp.wsgi --bind=unix:/var/run/gunicorn/gunicorn.sock"
  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  postgres-data:
