# Generated by Django 5.1.4 on 2025-01-12 14:20

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('chat', '0001_initial'), ('chat', '0002_alter_room_public_id'), ('chat', '0003_alter_room_public_id_message'), ('chat', '0004_alter_message_room_alter_room_public_id'), ('chat', '0005_alter_room_public_id'), ('chat', '0006_alter_room_public_id'), ('chat', '0007_alter_room_public_id'), ('chat', '0008_alter_room_public_id'), ('chat', '0009_alter_room_public_id'), ('chat', '0010_alter_room_public_id'), ('chat', '0011_alter_room_public_id'), ('chat', '0012_alter_room_public_id'), ('chat', '0013_alter_room_public_id'), ('chat', '0014_alter_room_public_id'), ('chat', '0015_alter_room_public_id'), ('chat', '0016_alter_room_public_id')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('public_id', chat.models.ULIDField(default=chat.models.ULIDField._generate_ulid, max_length=26, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room')),
            ],
        ),
    ]
